spring:
  profiles: primary
  application:
    name: demo-client
  zipkin:
    base-url: http://localhost:2000/
    enabled: true
  sleuth:
    sampler:
      percentage: 1
message: Hello world!111111111
server:
  port: 8084
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

logging:
  level:
    root: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG
