spring:
  profiles: primary
  zipkin:
    base-url: http://localhost:2000/
server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

---
spring:
  profiles: secondary
  zipkin:
      base-url: http://localhost:2000/
server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
