message: Hello world!111111111
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-primary:1111/eureka/,http://eureka-secondary:1112/eureka/,http://eureka-tertiary:1113/eureka/
spring:
  profiles: primary
  zipkin:
    base-url: http://localhost:2000/
