
spring:
  profiles: primary
  zipkin:
    base-url: http://localhost:2000/
    enabled: true
server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
logging:
  level:
    root: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG
---
spring:
  profiles: secondary
  zipkin:
      base-url: http://localhost:2000/
      enabled: true
server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
logging:
  level:
    root: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG
