spring:
  profiles: primary
  zipkin:
    base-url: http://localhost:2000/zipkin/
    enabled: true
message: Hello world!111111111
server:
  port: 8084
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
