spring:
  profiles: primary
server:
  port: 1111
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/,http://localhost:1112/eureka/

---
spring:
  profiles: secondary
server:
  port: 1112
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/,http://localhost:1112/eureka/
